apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-file-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-file-ms
  template:
    metadata:
      labels:
        app: property-file-ms
    spec:
      containers:
        - name: property-file-app
          image: property-file-docker:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8085