#general
logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: warn
    org.testcontainers: warn
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
info:
  app:
    name: property file comparator app
    description: compares property files
    java:
      version: 11
    type: Spring Boot

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

